name: hiking_dude_mobile
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: "0.5.2+1"
  firebase_auth: "^0.18.3+1"
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
    - family: UbuntuBold     
      fonts:
        - asset: fonts/Ubuntu-Bold.ttf
    - family: UbuntuRegular     
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
    - family: UbuntuMedium     
      fonts:
        - asset: fonts/Ubuntu-Medium.ttf
    - family: UbuntuLight     
      fonts:
        - asset: fonts/Ubuntu-Light.ttf

  assets:
    - assets/
